### ISSUE TITLE
Retrieving attachments

### ISSUE THREAD

**Issue by tyzion** [node-pop3/node-pop3#15]
Hi,
Is there a way to retrieve email attachments with this package?

**Comment by brettz9** [comment]
You can use its output (e.g., as from a RETR retrieval in [this test](https://github.com/brettz9/nogin/blob/master/test/utilities/EmailChecker.js#L61-L69) from another project) along with other tools such as https://github.com/jhermsmeier/node-envelope (noting though that the latter currently has [an issue](https://github.com/jhermsmeier/node-envelope/issues/32) reported stating that it is having problems with more than one attachment).

Closing as I think that may answer, but feel free to comment further as needed.

**Comment by tyzion** [comment]
Thank you for your prompt reply!
I searched a little and since i'm using Node, there's the mailparser module available  [https://nodemailer.com/extras/mailparser/](url)

**Comment by brettz9** [comment]
Envelope is also for Node, but it looks like mailparser has some heavy usage. Not sure how I missed that. Thanks for the info! By the way, for some reason, your link shows https://nodemailer.com/extras/mailparser/ but points back to this library.

**Comment by tyzion** [comment]
Sorry, i misused the link feature of comments!
I thought it was the way to put a link to urls... Evidently not 😅
Anyway, fixed that, and I also reached my primary goal!
Thanks for everything :)
