### ISSUE TITLE
Unhandled error event

### ISSUE THREAD

**Issue by tyzion** [node-pop3/node-pop3#18]
Hi, I don't know if this is an issue, but:
after polling for a while, it gives me this error, and i can't seem to catch and handle it.
Do you have a suggestion, or could you tell what do i do wrong?

`events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Disconnected for inactivity.
    at Socket.<anonymous> (/Users/.../src/server/node_modules/node-pop3/lib/Connection.js:176:24)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Emitted 'error' event on Pop3Command instance at:
    at Socket.<anonymous> (/Users/.../src/server/node_modules/node-pop3/lib/Connection.js:180:27)
    at Socket.emit (events.js:315:20)
    [... lines matching original stack trace ...]
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  eventName: 'error',
  command: 'PASS password'
}
[nodemon] app crashed - waiting for file changes before starting...`

**Comment by brettz9** [comment]
@lianxh do you know about this?

**Comment by tyzion** [comment]
Also, i don't know if this is related to the frequency of the polling, but sometimes it stucks on Auth ERR and keeps on for every call to pop3, and then the "Disconnected for inactivity message"

` Error: [AUTH] Authentication failed.
    at Socket.<anonymous> (/Users/.../src/server/node_modules/node-pop3/lib/Connection.js:176:24)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  eventName: 'error',
  command: 'PASS password'
}
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Disconnected for inactivity.
...`

**Comment by lianxh** [comment]
@tyzion it seems that the pop3 server has rejected your frequent requests. Maybe you should reduce the frequency of requests.

**Comment by tyzion** [comment]
I think i tried that, but I don't remember, i'll try again

@lianxh In the meantime can i ask you if you know how to handle this kind of error? 
Here's my code:

`
const DELAY = 60000;

async function run() {

    try{
        const pop3 = new Pop3Command({host: process.env.HOST});

        // this is how I tried to catch the unhandled event, but didn't give me any result
        await pop3.connect().catch(err => console.log('this is an err: ', err));
        await pop3.command('USER', process.env.POP3_USER);
        await pop3.command('PASS', process.env.POP3_PASS);

        }

        const [quitInfo, stream] = await pop3.command('QUIT')
        console.log(quitInfo)
        
        setTimeout(run, DELAY)

    } catch(err) {
        console.log('\n\n\n', err)
        setTimeout(run, DELAY)
    }
};
setTimeout(run, DELAY);
`

**Comment by tyzion** [comment]
I was able to catch it! I don't know why the first time i couldn't see it! but the catch on the pop3().connect works!
Sorry to have bothered you guys and thanks for the answers!
Don't know if it is in fact the frequency the problem, but today it hasn't given me any activity problem since now!
Anyway, thanks again :)
I think we can close this issue 👍

**Comment by tyzion** [comment]
Hi, sorry to bother you again
 I stopped working on my project for a while. I thought I was through with this problem, but I was wrong, I hadn't caught anything, I just consolled it.
Once I came back to my project I got the same error, no matter how frequent the poll was.
I tried to debug your project a little, but couldn't get anywhere.
What's different from before now is that now it gets disconnected not on the connect commands, but on the others. 
If you could help me again with this issue, that would be very much appreciated, thanks :)

**Comment by tyzion** [comment]
Ok, this time I really got the problem!
It was the fact that after I caught the error, I wasn't QUITting the POP3 session.
It took me 2 months figuring it out, but finally, I got it. Hope this will be helpful to others :)
