### ISSUE TITLE
ERR Command is  not valid in this state

### ISSUE THREAD

**Issue by Mr-zhao-dy** [node-pop3/node-pop3#33]
When I test this library with some mail just like xxx@outlook.com ,it gives me a error  response  '-ERR Command is  not valid in this state', will you plan to adaptation more mail type  like outlook?

**Comment by brettz9** [comment]
You should be able to get it to work by enabling POP settings: https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-for-outlook-com-d088b986-291d-42b8-9564-9c414e2aa040

**Comment by Mr-zhao-dy** [comment]
Thank you very much! I login success after adding certificates in params .

**Comment by brettz9** [comment]
Without sharing any private information, can you describe for us (as a helpful example) exactly how one may do this? I'm not familiar with it myself...

**Comment by Mr-zhao-dy** [comment]
just like this:

const __filename = fileURLToPath(import.meta.url);
// console.log("__filename: ", __filename);

const __dirname = path.dirname(__filename);
// console.log("__dirname: ", __dirname);

let path1 = path.resolve(__dirname, "./middle.pem");
let path2 = path.resolve(__dirname, "./root.pem");

const pop3 = new Pop3Command({
  // host: 'pop.qq.com',
   // port: 110,
  host: 'outlook.office365.com',
  port: 995,
  tls: true,
  tlsOptions: {
    ca: [fs.readFileSync(path1),fs.readFileSync(path2)],
    rejectUnauthorized: false
  }
});

// These must be in order
// let startTime = new Date().getTime()
await pop3.connect();
await pop3.command('USER', 'xxx@outlook.com');
await pop3.command('PASS', 'xxxxxxx');
const [statInfo] = await pop3.STAT();
await pop3.NOOP();
const [listInfo, listStream] = await pop3.LIST();
const [uidlInfo, uidlStream] = await pop3.UIDL('1');
// const [retrInfo, retrStream] = await pop3.RETR('1');
const [topInfo, topStream] = await pop3.RSET();

**Comment by Mr-zhao-dy** [comment]
By the way,I'm using your library in openharmony os,but have to do extra work to ensure your library  work well.It will be greate if you can provide a version which is adaptationing openharmony os .Thank you for your help!

**Comment by brettz9** [comment]
Thank you very much for the example.

Welcome to submit PRs (with tests if adding new functionality) for OpenHarmony compatibility, and we may hopefully be able to review.

**Comment by Mr-zhao-dy** [comment]
Thank you sir! When the time is right, I will try to submit my PR. Could you tell me the PR rules of your library first?

**Comment by brettz9** [comment]
No special rules—just using the mechanism through GitHub. And just to add tests for any new functionality.
